<template>
  <div class="divide-y-4 divide-black divide-opacity-25">
    <slot></slot>
    <div class="p-5">
      <label for="open">開啟ASS檔案</label>
      <input id="open" type="file" class="w-full min-h-2/3 bg-gray-200 px-4 py-2 rounded-lg" @change="handleFiles"/>
    </div>
    <div class="p-5">
      <label for="text">ASS文字內容</label>
      <textarea id="text" :value="ASSText"
                class="w-full min-h-2/3 bg-gray-200 px-4 py-2 rounded-lg"
                @change="setASSText"
      ></textarea>
    </div>
    <div class="p-5 flex flex-wrap justify-around">
      <div>
        <label for="size">字體大小</label>
        <div id="size" class="selector divide-x-4 divide-white">
          <button class="item" v-for="item in sizeOptions" :key="item.size" @click="setFontSize(item.size)"
                  :class="{'active':isActive(item.size)}"
          >
            {{ item.name }}
          </button>
        </div>
      </div>
      <div>
        <label for="color">字體顏色</label>
        <div id="color" class="selector divide-x-4 divide-white">
          <select :value="fontColor" class="bg-gray-200 px-4 py-2 rounded-lg" @change="setFontColorValue">
            <option v-for="item in colorOptions" :value="item.color" :label="item.name" :key="item.color"
                    :class="`bg-${item.color}-500`" class="text-white">
              {{ item.name }}
            </option>
          </select>
        </div>
      </div>
    </div>
    <div class="p-5">
      範例檔案：
      <ul class="mx-10 my-3 list-disc">
        <template v-for="item in examples">
          <li :key="item.id"><a class="cursor-pointer hover:underline" @click="setExample(item)">
            {{ item.name }}</a></li>
        </template>
      </ul>
    </div>
  </div>
</template>

<script>
import {mapActions, mapGetters} from "vuex";

export default {
  name: "settings",
  computed: {
    ...mapGetters(['ASSText', 'fontSize', 'fontColor']),
    sizeOptions() {
      return [
        {
          size: "lg",
          name: "大"
        },
        {
          size: "md",
          name: "中"
        },
        {
          size: "sm",
          name: "小"
        }
      ]
    },
    colorOptions() {
      return [
        {
          color: "blue",
          name: "藍"
        },
        {
          color: "red",
          name: "紅"
        },
        {
          color: "green",
          name: "綠"
        }
      ]
    },
    examples() {
      return [
        {
          id: 1,
          name: '告五人 - 在這座城市遺失了你',
          youtubeUrl: 'https://www.youtube.com/watch?v=PlCbgZxonJs',
          text: '[Script Info]\n' +
              '; Script generated by Aegisub 3.2.2\n' +
              '; http://www.aegisub.org/\n' +
              'Title: Default Aegisub file\n' +
              'ScriptType: v4.00+\n' +
              'WrapStyle: 0\n' +
              'ScaledBorderAndShadow: yes\n' +
              'YCbCr Matrix: None\n' +
              '\n' +
              '[Aegisub Project Garbage]\n' +
              'Audio File: yt1s.com - 告五人 Accusefive  在這座城市遺失了你 Where I Lost Us  Official Music Video_320kbps.mp3\n' +
              'Scroll Position: 35\n' +
              'Active Line: 69\n' +
              '\n' +
              '[V4+ Styles]\n' +
              'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n' +
              'Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n' +
              '\n' +
              '[Events]\n' +
              'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n' +
              'Dialogue: 0,0:00:41.94,0:00:44.94,Default,,0,0,0,,{\\k100}★{\\k100}★{\\k100}★\n' +
              'Dialogue: 0,0:00:44.94,0:00:47.90,Default,,0,0,0,,{\\k82}三{\\k82}番{\\k62}故{\\k82}里{\\k0}\n' +
              'Dialogue: 0,0:00:48.46,0:00:49.88,Default,,0,0,0,,{\\k35}窗{\\k36}外{\\k35}雨{\\k36}滴\n' +
              'Dialogue: 0,0:00:49.88,0:00:53.86,Default,,0,0,0,,{\\k32}打{\\k38}破{\\k42}細{\\k62}碎{\\k58}的{\\k72}玻{\\k94}璃{\\k0}\n' +
              'Dialogue: 0,0:00:55.84,0:00:58.54,Default,,0,0,0,,{\\k70}與{\\k40}你{\\k86}相{\\k74}遇\n' +
              'Dialogue: 0,0:00:58.93,0:01:00.52,Default,,0,0,0,,{\\k49}是{\\k42}在{\\k28}一{\\k40}個\n' +
              'Dialogue: 0,0:01:00.52,0:01:04.54,Default,,0,0,0,,{\\k30}單{\\k36}純{\\k64}美{\\k62}好{\\k32}的{\\k74}世{\\k104}界\n' +
              'Dialogue: 0,0:01:05.86,0:01:09.20,Default,,0,0,0,,{\\k32}而{\\k36}在{\\k64}變{\\k24}質{\\k70}那{\\k108}天\n' +
              'Dialogue: 0,0:01:10.12,0:01:14.90,Default,,0,0,0,,{\\k36}你{\\k28}淚{\\k48}流{\\k60}誇{\\k38}張{\\k60}情{\\k208}節\n' +
              'Dialogue: 0,0:01:16.46,0:01:19.40,Default,,0,0,0,,{\\k41}足{\\k33}以{\\k30}向{\\k40}全{\\k30}世{\\k33}界{\\k34}討{\\k53}回\n' +
              'Dialogue: 0,0:01:19.48,0:01:23.46,Default,,0,0,0,,{\\k43}你{\\k50}付{\\k80}出{\\k69}的{\\k22}一{\\k134}切\n' +
              'Dialogue: 0,0:01:27.84,0:01:30.56,Default,,0,0,0,,{\\k68}你{\\k68}的{\\k43}故{\\k93}事\n' +
              'Dialogue: 0,0:01:31.14,0:01:32.40,Default,,0,0,0,,{\\k31}存{\\k36}在{\\k38}一{\\k21}個\n' +
              'Dialogue: 0,0:01:32.40,0:01:36.89,Default,,0,0,0,,{\\k43}需{\\k41}要{\\k67}密{\\k69}碼{\\k33}的{\\k54}盒{\\k142}子\n' +
              'Dialogue: 0,0:01:38.36,0:01:41.22,Default,,0,0,0,,{\\k87}紀{\\k45}念{\\k62}時{\\k92}刻\n' +
              'Dialogue: 0,0:01:41.74,0:01:43.20,Default,,0,0,0,,{\\k39}打{\\k34}開{\\k40}卻{\\k33}會\n' +
              'Dialogue: 0,0:01:43.20,0:01:46.87,Default,,0,0,0,,{\\k32}冒{\\k39}出{\\k52}一{\\k50}陣{\\k97}陣{\\k37}白{\\k60}煙\n' +
              'Dialogue: 0,0:01:48.23,0:01:51.86,Default,,0,0,0,,{\\k60}像{\\k32}是{\\k41}警{\\k56}告{\\k66}自{\\k108}己\n' +
              'Dialogue: 0,0:01:52.86,0:01:54.00,Default,,0,0,0,,{\\k16}不{\\k14}能{\\k42}屈{\\k34}服\n' +
              'Dialogue: 0,0:01:54.00,0:01:57.23,Default,,0,0,0,,{\\k52}嚮{\\k32}往{\\k51}從{\\k155}前\n' +
              'Dialogue: 0,0:01:59.80,0:02:02.57,Default,,0,0,0,,{\\k46}天{\\k65}變{\\k69}地{\\k97}變\n' +
              'Dialogue: 0,0:02:02.84,0:02:04.59,Default,,0,0,0,,{\\k37}我{\\k35}們{\\k23}的{\\k53}愛\n' +
              'Dialogue: 0,0:02:04.78,0:02:05.95,Default,,0,0,0,,{\\k42}也{\\k75}變\n' +
              'Dialogue: 0,0:02:10.21,0:02:13.52,Default,,0,0,0,,{\\k55}而{\\k276}我\n' +
              'Dialogue: 0,0:02:14.14,0:02:15.85,Default,,0,0,0,,{\\k39}在{\\k36}這{\\k29}座{\\k30}城{\\k34}市\n' +
              'Dialogue: 0,0:02:15.85,0:02:18.32,Default,,0,0,0,,{\\k47}遺{\\k56}失{\\k80}了{\\k64}你\n' +
              'Dialogue: 0,0:02:19.42,0:02:22.22,Default,,0,0,0,,{\\k45}順{\\k36}便{\\k23}遺{\\k33}失{\\k35}了{\\k33}自{\\k75}己\n' +
              'Dialogue: 0,0:02:24.84,0:02:26.88,Default,,0,0,0,,{\\k35}以{\\k33}為{\\k34}荒{\\k34}唐{\\k34}到{\\k34}底\n' +
              'Dialogue: 0,0:02:27.21,0:02:28.22,Default,,0,0,0,,{\\k27}會{\\k74}有\n' +
              'Dialogue: 0,0:02:28.27,0:02:29.53,Default,,0,0,0,,{\\k58}捷{\\k68}徑\n' +
              'Dialogue: 0,0:02:31.21,0:02:35.21,Default,,0,0,0,,{\\k38}而{\\k362}我\n' +
              'Dialogue: 0,0:02:35.48,0:02:37.06,Default,,0,0,0,,{\\k38}在{\\k35}這{\\k26}座{\\k29}城{\\k30}市\n' +
              'Dialogue: 0,0:02:37.06,0:02:39.56,Default,,0,0,0,,{\\k65}失{\\k76}去{\\k43}了{\\k66}你\n' +
              'Dialogue: 0,0:02:40.64,0:02:44.10,Default,,0,0,0,,{\\k53}輸{\\k35}給{\\k32}慾{\\k34}望{\\k33}高{\\k33}漲{\\k32}的{\\k30}自{\\k64}己\n' +
              'Dialogue: 0,0:02:46.16,0:02:47.58,Default,,0,0,0,,{\\k24}不{\\k49}是{\\k69}你\n' +
              'Dialogue: 0,0:02:47.86,0:02:50.81,Default,,0,0,0,,{\\k59}過{\\k59}分{\\k47}的{\\k55}感{\\k75}情\n' +
              'Dialogue: 0,0:02:51.52,0:02:53.53,Default,,0,0,0,,{\\k33}而{\\k52}我{\\k84}愛{\\k31}你\n' +
              'Dialogue: 0,0:02:56.92,0:02:59.18,Default,,0,0,0,,{\\k28}而{\\k72}愛{\\k47}無{\\k79}法\n' +
              'Dialogue: 0,0:03:00.46,0:03:01.69,Default,,0,0,0,,{\\k63}撐{\\k60}起\n' +
              'Dialogue: 0,0:03:02.09,0:03:04.95,Default,,0,0,0,,{\\k39}想{\\k58}擁{\\k78}有{\\k84}的\n' +
              'Dialogue: 0,0:03:07.39,0:03:10.10,Default,,0,0,0,,{\\k40}想{\\k76}擁{\\k53}抱{\\k102}的\n' +
              'Dialogue: 0,0:03:13.88,0:03:15.42,Default,,0,0,0,,{\\k38}以{\\k30}為{\\k86}能\n' +
              'Dialogue: 0,0:03:16.38,0:03:17.80,Default,,0,0,0,,{\\k51}通{\\k91}向\n' +
              'Dialogue: 0,0:03:18.20,0:03:21.24,Default,,0,0,0,,{\\k39}領{\\k35}悟{\\k31}的{\\k57}結{\\k142}局\n' +
              'Dialogue: 0,0:03:21.24,0:03:42.29,Default,,0,0,0,,\n' +
              'Dialogue: 0,0:03:43.29,0:03:46.24,Default,,0,0,0,,{\\k100}★{\\k100}★{\\k100}★\n' +
              'Dialogue: 0,0:03:46.50,0:03:49.24,Default,,0,0,0,,{\\k70}你{\\k67}的{\\k50}故{\\k87}事\n' +
              'Dialogue: 0,0:03:49.91,0:03:51.06,Default,,0,0,0,,{\\k32}存{\\k31}在{\\k32}一{\\k20}個\n' +
              'Dialogue: 0,0:03:51.06,0:03:55.33,Default,,0,0,0,,{\\k43}需{\\k34}要{\\k64}密{\\k75}碼{\\k31}的{\\k59}盒{\\k121}子\n' +
              'Dialogue: 0,0:03:56.94,0:04:00.18,Default,,0,0,0,,{\\k83}紀{\\k64}念{\\k70}時{\\k107}刻\n' +
              'Dialogue: 0,0:04:00.55,0:04:01.80,Default,,0,0,0,,{\\k31}打{\\k31}開{\\k31}卻{\\k32}會\n' +
              'Dialogue: 0,0:04:01.80,0:04:06.22,Default,,0,0,0,,{\\k39}冒{\\k35}出{\\k65}一{\\k39}陣{\\k98}陣{\\k33}白{\\k133}煙\n' +
              'Dialogue: 0,0:04:07.06,0:04:10.54,Default,,0,0,0,,{\\k41}像{\\k34}是{\\k39}警{\\k64}告{\\k64}自{\\k115}己\n' +
              'Dialogue: 0,0:04:11.53,0:04:12.63,Default,,0,0,0,,{\\k13}不{\\k15}能{\\k41}屈{\\k24}服\n' +
              'Dialogue: 0,0:04:12.63,0:04:16.20,Default,,0,0,0,,{\\k48}嚮{\\k46}往{\\k50}從{\\k213}前\n' +
              'Dialogue: 0,0:04:18.50,0:04:21.16,Default,,0,0,0,,{\\k36}天{\\k72}變{\\k64}地{\\k94}變\n' +
              'Dialogue: 0,0:04:21.44,0:04:22.97,Default,,0,0,0,,{\\k40}我{\\k36}們{\\k31}的{\\k46}愛\n' +
              'Dialogue: 0,0:04:23.47,0:04:24.23,Default,,0,0,0,,{\\k40}也{\\k36}變\n' +
              'Dialogue: 0,0:04:28.86,0:04:31.91,Default,,0,0,0,,{\\k49}而{\\k256}我\n' +
              'Dialogue: 0,0:04:32.59,0:04:34.50,Default,,0,0,0,,{\\k56}在{\\k41}這{\\k24}座{\\k33}城{\\k37}市\n' +
              'Dialogue: 0,0:04:34.50,0:04:36.87,Default,,0,0,0,,{\\k41}遺{\\k59}失{\\k72}了{\\k65}你\n' +
              'Dialogue: 0,0:04:37.92,0:04:40.93,Default,,0,0,0,,{\\k61}順{\\k35}便{\\k34}遺{\\k25}失{\\k37}了{\\k27}自{\\k82}己\n' +
              'Dialogue: 0,0:04:43.54,0:04:45.49,Default,,0,0,0,,{\\k32}以{\\k28}為{\\k37}荒{\\k36}唐{\\k36}到{\\k26}底\n' +
              'Dialogue: 0,0:04:45.84,0:04:48.18,Default,,0,0,0,,{\\k34}會{\\k54}有{\\k67}捷{\\k79}徑\n' +
              'Dialogue: 0,0:04:50.17,0:04:53.51,Default,,0,0,0,,{\\k49}而{\\k285}我\n' +
              'Dialogue: 0,0:04:54.15,0:04:55.65,Default,,0,0,0,,{\\k37}在{\\k36}這{\\k27}座{\\k31}城{\\k19}市\n' +
              'Dialogue: 0,0:04:55.65,0:04:58.23,Default,,0,0,0,,{\\k69}失{\\k59}去{\\k62}了{\\k68}你\n' +
              'Dialogue: 0,0:04:59.39,0:05:02.88,Default,,0,0,0,,{\\k47}輸{\\k42}給{\\k25}慾{\\k30}望{\\k36}高{\\k36}漲{\\k27}的{\\k32}自{\\k74}己\n' +
              'Dialogue: 0,0:05:04.87,0:05:06.23,Default,,0,0,0,,{\\k19}不{\\k43}是{\\k74}你\n' +
              'Dialogue: 0,0:05:06.56,0:05:09.24,Default,,0,0,0,,{\\k54}過{\\k53}分{\\k57}的{\\k50}感{\\k54}情\n' +
              'Dialogue: 0,0:05:09.24,0:05:15.24,Default,,0,0,0,,\n' +
              'Dialogue: 0,0:05:15.24,0:05:33.92,Default,,0,0,0,,\n' +
              'Dialogue: 0,0:05:33.92,0:05:36.92,Default,,0,0,0,,{\\k100}★{\\k100}★{\\k100}★\n' +
              'Dialogue: 0,0:05:36.92,0:05:39.54,Default,,0,0,0,,{\\k33}而{\\k69}我{\\k62}愛{\\k98}你\n' +
              'Dialogue: 0,0:05:42.20,0:05:44.88,Default,,0,0,0,,{\\k35}而{\\k69}愛{\\k66}無{\\k98}法\n' +
              'Dialogue: 0,0:05:45.74,0:05:47.03,Default,,0,0,0,,{\\k54}撐{\\k75}起\n' +
              'Dialogue: 0,0:05:47.46,0:05:50.17,Default,,0,0,0,,{\\k42}想{\\k60}擁{\\k71}有{\\k205}的\n' +
              'Dialogue: 0,0:05:52.74,0:05:55.48,Default,,0,0,0,,{\\k39}想{\\k67}擁{\\k75}抱{\\k93}的\n' +
              'Dialogue: 0,0:05:59.20,0:06:01.51,Default,,0,0,0,,{\\k28}以{\\k39}為{\\k164}能\n' +
              'Dialogue: 0,0:06:01.90,0:06:03.14,Default,,0,0,0,,{\\k51}通{\\k73}向\n' +
              'Dialogue: 0,0:06:03.54,0:06:07.04,Default,,0,0,0,,{\\k38}領{\\k45}悟{\\k43}的{\\k43}結{\\k181}局\n' +
              'Dialogue: 0,0:06:07.04,0:06:09.04,Default,,0,0,0,,\n' +
              'Dialogue: 0,0:06:09.04,0:06:11.04,Default,,0,0,0,,\n'
        },
        {
          id:2,
          name:'茄子蛋 - 愛情你比我想的閣較偉大',
          youtubeUrl: 'https://www.youtube.com/watch?v=0rp3pP2Xwhs',
          text: '[Script Info]\n' +
              '; Script generated by Aegisub 3.2.2\n' +
              '; http://www.aegisub.org/\n' +
              'Title: Default Aegisub file\n' +
              'ScriptType: v4.00+\n' +
              'WrapStyle: 0\n' +
              'ScaledBorderAndShadow: yes\n' +
              'YCbCr Matrix: None\n' +
              '\n' +
              '[Aegisub Project Garbage]\n' +
              'Audio File: yt1s.com - 茄子蛋EggPlantEgg  愛情你比我想的閣較偉大 Official Music Video當男人戀愛時電影主題曲_320kbps.mp3\n' +
              'Scroll Position: 51\n' +
              'Active Line: 59\n' +
              '\n' +
              '[V4+ Styles]\n' +
              'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n' +
              'Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n' +
              '\n' +
              '[Events]\n' +
              'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n' +
              'Dialogue: 0,0:00:37.11,0:00:40.11,Default,,0,0,0,,{\\k100}★{\\k100}★{\\k100}★\n' +
              'Dialogue: 0,0:00:40.11,0:00:42.48,Default,,0,0,0,,{\\k18}倒{\\k22}佇{\\k29}故{\\k29}鄉{\\k37}街{\\k27}市{\\k26}的{\\k27}中{\\k27}央\n' +
              'Dialogue: 0,0:00:42.48,0:00:44.89,Default,,0,0,0,,{\\k23}笑{\\k20}看{\\k34}世{\\k41}界{\\k26}咧{\\k35}轉{\\k121}踅\n' +
              'Dialogue: 0,0:00:45.48,0:00:46.10,Default,,0,0,0,,{\\k17}你{\\k23}是{\\k54}我\n' +
              'Dialogue: 0,0:00:46.42,0:00:48.56,Default,,0,0,0,,{\\k27}烏{\\k18}暗{\\k17}的{\\k23}心{\\k36}唯{\\k27}一{\\k39}的{\\k27}光\n' +
              'Dialogue: 0,0:00:48.56,0:00:51.24,Default,,0,0,0,,{\\k28}親{\\k25}像{\\k20}是{\\k39}眼{\\k28}前{\\k28}的{\\k28}燈{\\k28}火\n' +
              'Dialogue: 0,0:00:52.06,0:00:54.85,Default,,0,0,0,,{\\k24}原{\\k21}諒{\\k35}我{\\k22}這{\\k22}款{\\k38}放{\\k24}蕩{\\k35}的{\\k74}人\n' +
              'Dialogue: 0,0:00:55.28,0:00:58.25,Default,,0,0,0,,{\\k22}原{\\k21}諒{\\k14}我{\\k22}做{\\k18}這{\\k24}款{\\k34}夭{\\k26}壽{\\k36}的{\\k80}夢\n' +
              'Dialogue: 0,0:00:58.25,0:01:01.52,Default,,0,0,0,,{\\k16}每{\\k28}一{\\k21}擺{\\k38}你{\\k23}的{\\k33}眼{\\k48}神{\\k39}咧{\\k41}振{\\k40}動\n' +
              'Dialogue: 0,0:01:01.52,0:01:04.29,Default,,0,0,0,,{\\k17}攏{\\k22}予{\\k19}我{\\k38}無{\\k24}法{\\k34}分{\\k40}西{\\k83}東\n' +
              'Dialogue: 0,0:01:04.29,0:01:05.28,Default,,0,0,0,,{\\k49}哦{\\k50}～\n' +
              'Dialogue: 0,0:01:05.68,0:01:08.10,Default,,0,0,0,,{\\k19}我{\\k25}用{\\k25}我{\\k34}的{\\k32}人{\\k27}格{\\k38}來{\\k15}保{\\k27}證\n' +
              'Dialogue: 0,0:01:08.10,0:01:10.82,Default,,0,0,0,,{\\k14}我{\\k20}是{\\k24}永{\\k41}遠{\\k43}袂{\\k37}後{\\k93}悔\n' +
              'Dialogue: 0,0:01:11.06,0:01:11.68,Default,,0,0,0,,{\\k14}你{\\k25}是{\\k23}我\n' +
              'Dialogue: 0,0:01:12.05,0:01:14.29,Default,,0,0,0,,{\\k20}目{\\k24}前{\\k19}為{\\k43}止{\\k16}的{\\k22}愛{\\k22}人{\\k19}內{\\k39}底\n' +
              'Dialogue: 0,0:01:14.29,0:01:16.89,Default,,0,0,0,,{\\k19}無{\\k17}疑{\\k20}是{\\k32}上{\\k37}水{\\k35}的{\\k36}彼{\\k64}個\n' +
              'Dialogue: 0,0:01:17.38,0:01:20.36,Default,,0,0,0,,{\\k29}我{\\k20}其{\\k20}實{\\k35}毋{\\k46}是{\\k41}毋{\\k22}願{\\k30}離{\\k55}開\n' +
              'Dialogue: 0,0:01:20.67,0:01:23.68,Default,,0,0,0,,{\\k24}攏{\\k20}怪{\\k17}你{\\k39}行{\\k21}入{\\k21}了{\\k39}我{\\k21}的{\\k31}人{\\k68}生\n' +
              'Dialogue: 0,0:01:23.89,0:01:26.90,Default,,0,0,0,,{\\k19}無{\\k15}心{\\k25}的{\\k39}愛{\\k38}情{\\k23}傷{\\k42}害{\\k33}已{\\k37}造{\\k30}成\n' +
              'Dialogue: 0,0:01:27.08,0:01:29.66,Default,,0,0,0,,{\\k21}你{\\k20}我{\\k19}著{\\k28}愛{\\k49}來{\\k23}負{\\k21}責{\\k77}任\n' +
              'Dialogue: 0,0:01:29.87,0:01:31.09,Default,,0,0,0,,{\\k61}哦{\\k61}～\n' +
              'Dialogue: 0,0:01:33.23,0:01:34.51,Default,,0,0,0,,{\\k91}哦{\\k112}～\n' +
              'Dialogue: 0,0:01:36.26,0:01:37.68,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:01:39.44,0:01:40.90,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:01:42.67,0:01:43.89,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:01:45.87,0:01:46.88,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:01:49.04,0:01:50.08,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:01:52.36,0:01:53.69,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:01:53.69,0:01:55.87,Default,,0,0,0,,{\\k72}★{\\k73}★{\\k73}★\n' +
              'Dialogue: 0,0:01:55.87,0:01:59.15,Default,,0,0,0,,{\\k18}愛{\\k18}情{\\k29}你{\\k39}比{\\k19}我{\\k18}想{\\k20}的{\\k23}閣{\\k19}較{\\k39}偉{\\k86}大\n' +
              'Dialogue: 0,0:01:59.15,0:02:02.42,Default,,0,0,0,,{\\k30}你{\\k22}予{\\k21}我{\\k17}這{\\k25}世{\\k14}人{\\k17}最{\\k26}後{\\k21}的{\\k40}期{\\k94}待\n' +
              'Dialogue: 0,0:02:02.42,0:02:04.19,Default,,0,0,0,,{\\k19}你{\\k28}是{\\k41}我{\\k22}的{\\k37}未{\\k30}來\n' +
              'Dialogue: 0,0:02:04.19,0:02:08.49,Default,,0,0,0,,{\\k30}希{\\k39}望{\\k26}你{\\k38}會{\\k57}了{\\k240}解\n' +
              'Dialogue: 0,0:02:08.76,0:02:11.76,Default,,0,0,0,,{\\k30}雖{\\k28}然{\\k92}江{\\k22}山{\\k21}易{\\k107}改\n' +
              'Dialogue: 0,0:02:12.07,0:02:15.23,Default,,0,0,0,,{\\k39}但{\\k96}本{\\k24}性{\\k25}難{\\k132}移\n' +
              'Dialogue: 0,0:02:15.23,0:02:18.09,Default,,0,0,0,,{\\k25}愛{\\k21}你{\\k40}愛{\\k21}甲{\\k41}白{\\k32}目{\\k87}眉\n' +
              'Dialogue: 0,0:02:18.09,0:02:19.25,Default,,0,0,0,,{\\k61}哦{\\k61}～\n' +
              'Dialogue: 0,0:02:21.39,0:02:22.67,Default,,0,0,0,,{\\k91}哦{\\k112}～\n' +
              'Dialogue: 0,0:02:24.42,0:02:25.84,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:02:27.60,0:02:29.06,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:02:30.83,0:02:32.05,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:02:34.03,0:02:35.04,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:02:37.20,0:02:38.24,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:02:40.52,0:02:41.85,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:02:43.44,0:02:44.31,Default,,0,0,0,,{\\k72}哦{\\k70}～\n' +
              'Dialogue: 0,0:02:44.57,0:03:00.57,Default,,0,0,0,,\n' +
              'Dialogue: 0,0:03:00.57,0:03:06.57,Default,,0,0,0,,\n' +
              'Dialogue: 0,0:03:06.57,0:03:09.57,Default,,0,0,0,,{\\k100}★{\\k100}★{\\k100}★\n' +
              'Dialogue: 0,0:03:09.57,0:03:12.83,Default,,0,0,0,,{\\k14}愛{\\k19}情{\\k22}你{\\k39}比{\\k15}我{\\k25}想{\\k16}的{\\k23}閣{\\k17}較{\\k40}偉{\\k96}大\n' +
              'Dialogue: 0,0:03:12.83,0:03:16.03,Default,,0,0,0,,{\\k26}你{\\k20}予{\\k20}我{\\k14}這{\\k26}世{\\k14}人{\\k21}最{\\k18}後{\\k27}的{\\k40}期{\\k94}待\n' +
              'Dialogue: 0,0:03:16.03,0:03:17.92,Default,,0,0,0,,{\\k23}你{\\k23}是{\\k36}我{\\k27}的{\\k40}未{\\k40}來\n' +
              'Dialogue: 0,0:03:17.92,0:03:22.40,Default,,0,0,0,,{\\k18}希{\\k39}望{\\k21}你{\\k40}會{\\k56}了{\\k274}解{\\k0}\n' +
              'Dialogue: 0,0:03:22.45,0:03:25.56,Default,,0,0,0,,{\\k23}雖{\\k20}然{\\k101}江{\\k20}山{\\k21}易{\\k126}改\n' +
              'Dialogue: 0,0:03:25.56,0:03:28.81,Default,,0,0,0,,{\\k46}但{\\k104}本{\\k23}性{\\k17}難{\\k135}移\n' +
              'Dialogue: 0,0:03:28.81,0:03:32.02,Default,,0,0,0,,{\\k27}愛{\\k19}你{\\k41}愛{\\k16}甲{\\k39}白{\\k45}目{\\k134}眉 {\\k0}\n' +
              'Dialogue: 0,0:03:32.02,0:03:35.25,Default,,0,0,0,,{\\k22}毋{\\k23}管{\\k102}你{\\k27}知{\\k18}毋{\\k131}知\n' +
              'Dialogue: 0,0:03:35.25,0:03:38.41,Default,,0,0,0,,{\\k26}予{\\k20}你{\\k100}全{\\k22}部{\\k19}的{\\k129}愛\n' +
              'Dialogue: 0,0:03:38.41,0:03:41.28,Default,,0,0,0,,{\\k28}愛{\\k22}你{\\k37}愛{\\k21}甲{\\k41}白{\\k24}目{\\k114}眉\n' +
              'Dialogue: 0,0:03:41.28,0:03:43.28,Default,,0,0,0,,\n' +
              'Dialogue: 0,0:03:43.28,0:03:45.28,Default,,0,0,0,,\n'
        },
        {
          id:3,
          name:'八三夭 - 想見你想見你想見你',
          youtubeUrl: 'https://www.youtube.com/watch?v=4iRupuNet3Q',
          text: ''
        }
      ]
    }
  },
  methods: {
    ...mapActions(['setYoutubeURL', 'setASSText', 'setFontSize', 'setFontColor']),
    handleFiles(event) {
      let reader = new FileReader();
      reader.readAsText(event.target.files[0], "UTF-8")
      reader.onload = (e) => {
        this.setASSText(e.target.result)
      }
    },
    async setExample(item) {
      await this.setYoutubeURL('')
      await this.setASSText('')
      await this.setYoutubeURL(item.youtubeUrl)
      await this.setASSText(item.text)
    },
    isActive(size) {
      return this.fontSize === size
    },
    setFontColorValue(event) {
      this.setFontColor(event.target.value)
    }
  }
}
</script>

<style lang="scss" scoped>
.selector {
  .item {
    @apply bg-gray-200 px-4 py-2;
    &.active {
      @apply bg-blue-500 text-white;
    }

    &:first-child {
      @apply rounded-l-lg;
    }

    &:last-child {
      @apply rounded-r-lg;
    }
  }
}
</style>
